### ISSUE TITLE
Component does not always receive updated props when using nuclearComponent decorator

### ISSUE THREAD

**Issue by plongyear** [jordangarcia/nuclear-js-react-addons#10]
I have run into a case where a component will not receive updated props via a getter if it is using the `nuclearComponent` decorator. This happens when a component calls an action that updates data in the store that its getter is pulling data from in its constructor or in the `componentWillMount`/`componentDidMount` functions.

Here is an example. `defaultFooValue` is passed in as a prop to `FooView`. `FooView` calls an action that sets the given `defaultFooValue` in the store and there is a `foo` getter that pulls the value out of the store.

```
import { getters, actions } from './myModule';
import { provideReactor, nuclearComponent } from 'nuclear-js-react-addons';

@provideReactor
@nuclearComponent({
    foo: getters.foo,
})
class FooView extends React.Component {
    constructor(args) {
        super(args)
        actions.setInitialFooValue(args.defaultFooValue)
    }

    render() {    
        return (
            <div>{this.props.foo}</div>
        )
    }
}
```

From what I've seen, the `FooView` component will render once with whatever default value is provided for `foo` in the store. It does not render a second time once `actions.setInitialFooValue(args.defaultFooValue)` updates `foo`'s value in the store.

If I create a parent component that calls `actions.setInitialFooValue` and then instantiate a `FooView`, the `FooView` instance will get the correct value from its getter.

I'm curious if this is intended behavior. Is it not possible for a component to listen to a getter and update data in the constructor or elsewhere that its getter is using?

**Comment by Sinewyk** [comment]
The value is correct. But by the time you call the action that mutate your state the observer is not yet watching, because the observe are called in the componentDidMount lifecycle.

You could make sure by putting a breakpoint inside the nuclearComponent componentDidMount lifecycle, and inside your constructor. Pretty sure your action is called when your component was not yet mounted.

As always. Either it's application state, in this case you should not do the action in your constructor, because it's unrelated to your component lifecycle. Or it's UI state that gets trashed when your component unmounts, which would make it simply React state unrelated to nuclear-js.

**Comment by Sinewyk** [comment]
I don't think it's _intended_ behavior as I never would use an application _synchronous_ action inside a constructor (why didn't you do it before if it's application state ?). But I do think you have a problem of where you keep your state.

**Comment by plongyear** [comment]
@Sinewyk, I have moved the action call outside of the component - It does make more sense that way when thinking about the entire application's state. Thanks for the explanation.

I'll go ahead and close this issue as it seems like this is not the preferred way to preload data in a store.

**Comment by Sinewyk** [comment]
No problem.
